name:                haskell-hackerrank
version:             0.1.0.0
github:              "RiccardoBiosas/haskell-hackerrank"
license:             BSD3
author:              "RiccardoBiosas"
maintainer:          "rbios@protonmail.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RiccardoBiosas/haskell-hackerrank#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  algo-02-exe:
    main:                Main.hs
    source-dirs:         src/algo-02
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hackerrank

  algo-03-exe:
    main:                Main.hs
    source-dirs:         src/algo-03
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hackerrank

  algo-04-exe:
    main:                Main.hs
    source-dirs:         src/algo-04
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hackerrank

  algo-05-exe:
    main:                Main.hs
    source-dirs:         src/algo-05
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-hackerrank

